version: "2.2"

services:
  v2ray:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-1080:1080}"
    volumes:
      - ./config:/etc/v2ray
      - ./log:/var/log/v2ray

